"""init schema (users, check_ins)

Revision ID: 01f3bdd49d0c
Revises: 
Create Date: 2026-05-05 22:31:19.490566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.db


# revision identifiers, used by Alembic.
revision: str = '01f3bdd49d0c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('created_at', app.db.UtcDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.create_table('check_ins',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('picked_up_by_user_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('override', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.db.UtcDateTime(), nullable=False),
    sa.Column('approved_at', app.db.UtcDateTime(), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'approved', 'cancelled')", name='ck_check_ins_status'),
    sa.ForeignKeyConstraint(['picked_up_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_check_ins_picked_up_by_user_id'), 'check_ins', ['picked_up_by_user_id'], unique=False)
    op.create_index('ix_check_ins_picked_up_by_user_id_created_at', 'check_ins', ['picked_up_by_user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_check_ins_user_id'), 'check_ins', ['user_id'], unique=False)
    op.create_index('ix_check_ins_user_id_created_at', 'check_ins', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_check_ins_user_id_created_at', table_name='check_ins')
    op.drop_index(op.f('ix_check_ins_user_id'), table_name='check_ins')
    op.drop_index('ix_check_ins_picked_up_by_user_id_created_at', table_name='check_ins')
    op.drop_index(op.f('ix_check_ins_picked_up_by_user_id'), table_name='check_ins')
    op.drop_table('check_ins')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
